[package]
name = "vibe"
version = "0.0.6"
edition = "2021"

[[bin]]
name = "main"
path = "bin/main.rs"

[lib]
name = "vibe"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.79"
ffmpeg-next = "6.1.1"
futures-util = "0.3.30"
hound = "3.5.1"
log = "0.4.20"
reqwest = { version = "0.11.23", features = ["stream"] }
sha256 = "1.5.0"
tempfile = "3.9.0"
tokio = { version = "1.35.1", features = [
    "tokio-macros",
    "macros",
    "rt",
    "rt-multi-thread",
] }
whisper-rs = { git = "https://github.com/thewh1teagle/whisper-rs", branch = "feat/get-segment-text-lossy" }
clap = { version = "4.4.13", features = ["derive"] }
env_logger = "0.10.1"
serde = { version = "1.0.195", features = ["derive"] }
num = "0.4.1"
once_cell = "1.19.0"
dirs-next = "2.0.0"


[features]
coreml = ["whisper-rs/coreml"]
cuda = ["whisper-rs/cuda"]
opencl = ["whisper-rs/opencl"]
openblas = ["whisper-rs/openblas"]
metal = ["whisper-rs/metal"]
static = ["ffmpeg-next/static"]
