[package]
name = "vibe"
version = "0.1.0"
edition = "2021"

[lib]
name = "vibe"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.79"
app_dirs2 = "2.5.5"
ffmpeg-next = "6.1.1"
futures-util = "0.3.30"
hound = "3.5.1"
indicatif = "0.17.7"
log = "0.4.20"
reqwest = { version = "0.11.23", features = ["stream"] }
sha256 = "1.5.0"
tempfile = "3.9.0"
tokio = { version = "1.35.1", features = ["tokio-macros", "macros", "rt", "rt-multi-thread"] }
whisper-rs = {git = "https://github.com/thewh1teagle/whisper-rs", branch = "fix/msys2-build"}
clap = { version = "4.4.13", features = ["derive"] }