[package]
name = "vibe-desktop"
version = "0.0.6"
description = "Vibe"
authors = ["@thewh1teagle"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "=2.0.0-beta.12", features = [] }
[dependencies]
tauri = { version = "=2.0.0-beta.15", features = ["protocol-asset"] }
tauri-plugin-window-state = "=2.0.0-beta.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.35.1"
once_cell = "1.19.0"
env_logger = "0.10.1"
log = "0.4.20"
tauri-plugin-fs = "2.0.0-beta.3"
tauri-plugin-updater = "2.0.0-beta.3"
tauri-plugin-dialog = "2.0.0-beta.3"
tauri-plugin-process = "2.0.0-beta.3"
tauri-plugin-os = "2.0.0-beta.3"
tauri-plugin-shell = "2.0.0-beta.3"


[target.'cfg(target_os = "linux")'.dependencies]
vibe = { path = "../../core", features = ["openblas"] }
openssl = { version = "0.10.63", features = ["vendored"] }

[target.'cfg(target_os = "windows")'.dependencies]
vibe = { path = "../../core", features = ["opencl"] }

[target.'cfg(target_os = "macos")'.dependencies]
vibe = { path = "../../core", features = ["coreml"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
